language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t psharp760/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true psharp760/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-1-735165036301"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"